//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly-typed resource accessor. Hand-maintained for CLI build compatibility.
//     Keys must mirror entries in Strings.resx.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace SIDM.App.Resources;

public static class Strings
{
    private static readonly ResourceManager _rm = new(
        "SIDM.App.Resources.Strings",
        typeof(Strings).Assembly);

    public static CultureInfo? Culture { get; set; }

    public static string Main_Greeting_Format => Get(nameof(Main_Greeting_Format));
    public static string Main_Tagline => Get(nameof(Main_Tagline));
    public static string Common_Pause => Get(nameof(Common_Pause));
    public static string Common_Resume => Get(nameof(Common_Resume));
    public static string Common_Cancel => Get(nameof(Common_Cancel));

    private static string Get(string key) =>
        _rm.GetString(key, Culture) ?? $"!{key}!";
}
